name: Delete Stale Branches
on: 
  push:
    branches:
      - 'main'


jobs:
  delete-branch:
    name: Delete Branch
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
                  
      - name: delete stale branches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          IGNORE_BRANCHES=${{ vars.IGNORE_BRANCHES_DELETE }}
          
            
          IFS=',' read -r -a ignore_branches <<< "$IGNORE_BRANCHES"
            
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            echo "Checking branch: $branch"
            
            if [ "$branch" == "main" ]; then
              echo "Branch $branch is the default branch, skip deletion"
              continue
            fi
              
            branch_ignore=false
            for ign_brn in "${ignore_branches[@]}"; do
              if [[ "$branch" == "$ign_brn"* ]]; then
                echo "Branch $branch starts with ignored prefix $ign_brn, skip deletion"
                branch_ignore=true
                break
              fi
            done
            
            if [ "$branch_ignore" == true ]; then
              continue
            fi
              
            git checkout $branch
              
            check_commit=$(git log --since="${{ vars.STALE_BRANCHES_KEEP_DAYS }} days ago" --oneline)
            if [ -z "$check_commit" ]; then
              echo "No commit history present from last ${{ vars.STALE_BRANCHES_KEEP_DAYS }} days"
              
              open_pr=$(gh pr list --head $branch --state open)
              if [ -z "$open_pr" ]; then
                echo "No Open pull request for the $branch"
                echo "Deleting the $branch"
                git push origin --delete $branch
                echo "Branch is deleted successfully"
                             
              else
                echo "Open pull request is present for the $branch. Skip deletion"
              fi
            else
              echo "Commits are present for $branch. Skip Deletion"
            fi
          done
