name: Github Actions Demo
on: workflow_dispatch

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get list of branches
              run: |
                 for branch in $(git branch -r); do
                     echo "Branch: $branch"
                 done
            
