name: Github Actions Demo
on: workflow_dispatch

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Get list of branches
              run: |
                 git branch
            
