name: Delete Stale Branches
on:
    push:
        branches:
            - 'main'

jobs:
    delete-branch:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
              
            - name: delete stale branches
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                 IGNORE_BRANCHES=${{ vars.IGNORE_BRANCHES_DELETE }}
                 ignore_branch=($(echo "$IGNORE_BRANCHES" | tr ',' '\n'))
                 echo "$ignore_branch"
                 
                 for branch in $(git branch -r | grep -v '\->'); do
                     echo "Checking branch: $branch"

                     echo "${ignore_branch[@]}"
                     if [ "${ignore_branch[@]}" == "${branch}" ]; then
                         echo "skip deletion of branch $branch"
                         continue
                     fi
                     
                     git checkout $branch
                     
                     check_commit=$(git log --since="14 days ago" --oneline)
                     if [ -z "$check_commit" ]; then
                         echo "No commit history present from last 14 days"
                         
                         open_pr=$(gh pr list --head $branch --state open)
                         if [ -z "$open_pr" ]; then
                             echo "No Open pull request for the $branch"
                             echo "Deleting the $branch"
                             git push origin --delete $branch
                             echo "Branch is deleted successfully"
                             
                         else
                             echo "Open pull request is present for the $branch. Skip deletion"
                         fi
                     else
                         echo "Commits are present for $branch. Skip Deletion"
                     fi
                 done
            
