name: Github Actions Demo
on: workflow_dispatch

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install gh cli
              run:
                  sudo apt-get install -y gh
                  
            - name: Get list of branches
              run: |
                 for branch in $(git branch -r); do
                     echo "Branch: $branch"
                     git checkout $branch #checkout each branches
                     check_commit=$(git log --since="14 days ago" --oneline)
                     if [ -z "$check_commit" ]; then
                         echo "No commit history in last 14 days"
                         
                     else
                         echo "Commits are present move to next branch"
                         open_pr=$(gh pr list --head $branch --state open)
                         if [ -z "$open_pr" ]; then
                             echo "No Open pull request for the branch"
                         fi
                     fi
                 done
            
